# Configuration for the ackermann_steering_controller.
ackermann_steering_controller:
  type        : "ackermann_steering_controller/AckermannSteeringController"

  # Joints
  rear_wheel: 'ackermann_wheel_joint'
  front_steer: 'ackermann_steer_joint'

  # Odometry related 
  publish_rate: 50                    # default: 50.0
  open_loop: true

  # Odometry covariances for the encoder output of the robot.
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation between the rear and the front, and diameter of the rear. 
  # These are both optional.
  # ackermann_steering_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter.
  # Geometry
  wheel_separation_h : 0.654
  wheel_radius : 0.167

  # Wheel separation and radius multipliers for odometry calibration.
  wheel_separation_h_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Steer position angle multipliers for fine tuning.
  steer_pos_multiplier       : 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: 'base_link' #default: base_link


  # Transform from odom -> base_link
  # Odom frame_id
  enable_odom_tf: true
  odom_frame_id: '/odom'

  # Set to false if the motor driver provides velocity data. 
  estimate_velocity_from_position: true

  # Commands
  publish_cmd: true
  allow_multiple_cmd_vel_publishers: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 5.0  # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2
      # has_jerk_limits        : true
      # max_jerk               : 5.0 # m/s^3

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2
      # has_jerk_limits        : true
      # max_jerk               : 2.5 # rad/s^3


    # Other (undocumented but in source code)
    # velocity_rolling_window_size: 10
    # cmd_vel_timeout: 0.5

    # Deprecated...
    publish_wheel_joint_controller_state: false