<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="constants">

	<!-- Math constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="math_pi" value="3.141592653589793" />
	<xacro:property name="math_pi_over_2" value="1.5707963267948966" />
	<xacro:property name="math_pi_over_4" value="0.785398163397448" />
	<xacro:property name="math_pi_over_6" value="${(math_pi/(6.0))}" />
	<xacro:property name="math_pi_over_6_29" value="0.51" />

	<!-- Chassis properties -->
	<xacro:property name="chassis_height" value="0.311"/>
	<!--xacro:property name="chassis_height" value="0.470"/-->
	<!--xacro:property name="chassis_height" value="0.411"/-->
	<xacro:property name="chassis_length" value="1.150"/>
	<xacro:property name="chassis_width" value="0.632"/>
	<xacro:property name="chassis_mass" value="100.00"/>
	<xacro:property name="robot_height_truth_ground" value="0.632"/>
	<xacro:property name="chassis_to_ground" value="${(robot_height_truth_ground - (chassis_height/2))}"/>


	<!-- Caster wheel properties -->
	<xacro:property name="caster_radius" value="0.020"/>
	<xacro:property name="caster_mass" value="0.09"/>
	<xacro:property name="caster_offsetX" value="0.045"/>

	<!-- 13" geared Wheels properties -->
	<xacro:property name="wheel_width" value="0.105"/>
	<xacro:property name="wheel_radius" value="0.167"/>
	<xacro:property name="wheel_diameters" value="0.334"/>
	<xacro:property name="wheel_mass" value="6.00"/>
	<xacro:property name="wheel_offsetY" value="0.020"/>
	<xacro:property name="wheel_offsetX" value="0.020"/>

	<!-- Ultrasonic sensor -->
	<xacro:property name="sonar_mass" value="0.05"/>
	<xacro:property name="sonar_length" value="0.007"/>
	<xacro:property name="sonar_width" value="0.015"/>
	<xacro:property name="sonar_height" value="0.009"/>
	<xacro:property name="sonar_offsetX" value="0.066"/>
	<!-- xacro:property name="sonarOffsetZ" value="0.0496"/ -->

	<xacro:property name="x_reference_heading" value="90.0" />

	<!-- Joint position -->
	<xacro:property name="pos_x_joint" value="${((chassis_length / 2)- wheel_radius)}"/>
	<xacro:property name="pos_y_joint" value="${((chassis_width / 2) - (wheel_width / 2))}"/>
	<xacro:property name="pos_z_joint" value="-${chassis_to_ground - wheel_radius}"/>


</robot>