<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel">

    <xacro:include filename="$(find fellahbot_description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find fellahbot_description)/urdf/inertials.xacro"/>


    <xacro:macro name="front_steer_wheel" params="prefix parent reflect ">

        <xacro:property name="pos_x_joint" value="${((chassis_length / 2)- wheel_radius)}"/>
        <xacro:property name="pos_y_joint" value="${((chassis_width / 2) - (wheel_width / 2))}"/>
        <xacro:property name="pos_z_joint" value="-${chassis_to_ground - wheel_radius}"/>


        <link name="front_${prefix}_steer">
            <visual>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Caster_Part-Body.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Caster_Part-Body.dae"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="6"/>
        </link>

        <joint name="front_${prefix}_steer_joint" type="revolute">
            <parent link="${parent}"/>
            <child link="front_${prefix}_steer"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${math_pi_over_6}" upper="${math_pi_over_6}" velocity="5.0" effort="10.0"/>
            <origin xyz="0.319 ${(reflect * 0.175)} 0.0"/>
        </joint>


        <transmission name="front_${prefix}_steer_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="front_${prefix}_steer_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="front_${prefix}_steer_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <motorTorqueConstant>1.o</motorTorqueConstant>
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </actuator>
        </transmission>



        <link name="front_${prefix}_wheel">
            <visual>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Geared_Hub_Motor-Fusion001.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Geared_Hub_Motor-Fusion001.dae"/>
                </geometry>
            </collision>
            <xacro:solid_cylinder_inertial rpy="0 0 0" xyz="0.0 0.0 -0.192" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}" />

        </link>


        <joint name="front_${prefix}_wheel_joint" type="continuous">
            <parent link="front_${prefix}_steer"/>
            <child link="front_${prefix}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="0.0 0.0 -0.192" rpy="0 0 0"/>
            <limit effort="10" velocity="10"/>
            <joint_properties damping="0.01" friction="0.0"/>
        </joint>



        <transmission name="front_${prefix}_wheel_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="front_${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="front_${prefix}_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <motorTorqueConstant>1.o</motorTorqueConstant>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>


    </xacro:macro>





    <xacro:macro name="rear_wheel" params="prefix parent reflect ">

        <xacro:property name="pos_x_joint" value="${((chassis_length / 2)- wheel_radius)}"/>
        <xacro:property name="pos_y_joint" value="${((chassis_width / 2) - (wheel_width / 2))}"/>
        <xacro:property name="pos_z_joint" value="-${chassis_to_ground - wheel_radius}"/>


        <link name="rear_${prefix}_wheel">
        <visual>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Geared_Hub_Motor-Fusion001.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://fellahbot_description/meshes/Fellahbot_DAE/Parts/Geared_Hub_Motor-Fusion001.dae"/>
                </geometry>
            </collision>
            <xacro:solid_cylinder_inertial rpy="0 0 0" xyz="-0.335 ${(reflect * 0.17523)} -0.192" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}" />

        </link>


        <joint name="rear_${prefix}_wheel_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="rear_${prefix}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="-0.335 ${(reflect * 0.17523)} -0.192" rpy="0 0 0"/>
            <limit effort="10" velocity="10"/>
            <joint_properties damping="0.01" friction="0.0"/>
        </joint>


        <transmission name="rear_${prefix}_wheel_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="rear_${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="rear_${prefix}_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <motorTorqueConstant>1.o</motorTorqueConstant>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>


    </xacro:macro>


</robot>